"""adjust table rev add column for fk

Revision ID: 01617ac91686
Revises: c8d942412261
Create Date: 2022-08-18 21:11:38.801850

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "01617ac91686"
down_revision = "c8d942412261"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("product_reviews", sa.Column("item", sa.Integer(), nullable=False))
    op.create_foreign_key(None, "product_reviews", "users", ["item"], ["id"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "product_reviews", type_="foreignkey")
    op.drop_column("product_reviews", "item")
    # ### end Alembic commands ###
