"""try constraint

Revision ID: 123832d66958
Revises: 6391da908259
Create Date: 2022-08-21 13:02:48.538971

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '123832d66958'
down_revision = '6391da908259'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product_details', 'stock')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_details', sa.Column('stock', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
