"""adjust table price

Revision ID: 3d2bf9277abc
Revises: 84daea9db722
Create Date: 2022-08-21 10:48:15.307601

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3d2bf9277abc'
down_revision = '84daea9db722'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_details', sa.Column('item_id', sa.Integer(), nullable=False))
    op.alter_column('product_details', 'stock',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('product_details', 'discount',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('product_details', 'discount_end_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.create_foreign_key(None, 'product_details', 'products', ['item_id'], ['id'])
    op.add_column('product_reviews', sa.Column('review', sa.Text(), nullable=False))
    op.drop_column('product_reviews', 'likes')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_reviews', sa.Column('likes', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_column('product_reviews', 'review')
    op.drop_constraint(None, 'product_details', type_='foreignkey')
    op.alter_column('product_details', 'discount_end_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('product_details', 'discount',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('product_details', 'stock',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('product_details', 'item_id')
    # ### end Alembic commands ###
