"""remove constraints

Revision ID: 5e8477bb6381
Revises: b35ca7bc9f89
Create Date: 2022-08-07 16:08:34.572240

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "5e8477bb6381"
down_revision = "b35ca7bc9f89"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("products", "sku", existing_type=sa.INTEGER(), nullable=False)
    op.alter_column("products", "review", existing_type=sa.INTEGER(), nullable=False)
    op.drop_constraint("products_sku_fkey", "products", type_="foreignkey")
    op.drop_constraint("products_review_fkey", "products", type_="foreignkey")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(
        "products_review_fkey", "products", "product_reviews", ["review"], ["id"]
    )
    op.create_foreign_key(
        "products_sku_fkey", "products", "product_details", ["sku"], ["id"]
    )
    op.alter_column("products", "review", existing_type=sa.INTEGER(), nullable=True)
    op.alter_column("products", "sku", existing_type=sa.INTEGER(), nullable=True)
    # ### end Alembic commands ###
