"""move price add start disc

Revision ID: 6391da908259
Revises: 3d2bf9277abc
Create Date: 2022-08-21 12:37:15.245813

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6391da908259'
down_revision = '3d2bf9277abc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_details', sa.Column('discount_start_date', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.drop_column('product_details', 'price')
    op.add_column('products', sa.Column('price', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'price')
    op.add_column('product_details', sa.Column('price', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_column('product_details', 'discount_start_date')
    # ### end Alembic commands ###
