"""empty message

Revision ID: 6585c92af6fb
Revises: 137bc2d70473
Create Date: 2022-08-02 20:27:21.530996

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6585c92af6fb'
down_revision = '137bc2d70473'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_products',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], )
    )
    op.alter_column('employees', 'user_role',
               existing_type=postgresql.ENUM('owner', 'manager', 'senior', 'worker', name='employeeroles'),
               nullable=True)
    op.alter_column('employees', 'user_groups',
               existing_type=postgresql.ENUM('luminaire', 'power_tool', 'garden_tool', 'paint', name='productgroup'),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('employees', 'user_groups',
               existing_type=postgresql.ENUM('luminaire', 'power_tool', 'garden_tool', 'paint', name='productgroup'),
               nullable=False)
    op.alter_column('employees', 'user_role',
               existing_type=postgresql.ENUM('owner', 'manager', 'senior', 'worker', name='employeeroles'),
               nullable=False)
    op.drop_table('user_products')
    # ### end Alembic commands ###
