"""adjust rating to likes

Revision ID: 84daea9db722
Revises: a48662f2ab5e
Create Date: 2022-08-20 20:51:20.256952

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "84daea9db722"
down_revision = "a48662f2ab5e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("product_reviews", sa.Column("likes", sa.Text(), nullable=False))
    op.drop_column("product_reviews", "review")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "product_reviews",
        sa.Column("review", sa.TEXT(), autoincrement=False, nullable=False),
    )
    op.drop_column("product_reviews", "likes")
    # ### end Alembic commands ###
