"""add relationship

Revision ID: a48662f2ab5e
Revises: 841cadb96972
Create Date: 2022-08-20 14:32:46.931126

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a48662f2ab5e'
down_revision = '841cadb96972'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_reviews_relation_table',
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.Column('comment_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['comment_id'], ['product_reviews.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['products.id'], )
    )
    op.drop_column('products', 'review')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('review', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_table('product_reviews_relation_table')
    # ### end Alembic commands ###
