"""fix db

Revision ID: b0f3b04990aa
Revises: 
Create Date: 2022-08-07 14:14:03.402422

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0f3b04990aa'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=12), nullable=False),
    sa.Column('first_name', sa.String(length=14), nullable=False),
    sa.Column('mid_name', sa.String(length=14), nullable=False),
    sa.Column('last_name', sa.String(length=14), nullable=False),
    sa.Column('user_role', sa.Enum('owner', 'manager', 'senior', 'worker', name='employeeroles'), nullable=True),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('phone', sa.String(length=10), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone'),
    sa.UniqueConstraint('username')
    )
    op.create_table('groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('groups', sa.Enum('luminaire', 'power_tool', 'garden_tool', 'paint', name='productgroups'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('stock', sa.Integer(), nullable=False),
    sa.Column('discount', sa.Float(), nullable=False),
    sa.Column('discount_end_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=14), nullable=False),
    sa.Column('last_name', sa.String(length=14), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('phone', sa.String(length=10), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('created_on', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone')
    )
    op.create_table('employee_product_groups',
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('user_groups', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_groups'], ['groups.id'], ),
    sa.ForeignKeyConstraint(['username'], ['employees.username'], ),
    sa.PrimaryKeyConstraint('username', 'user_groups')
    )
    op.create_table('product_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('review', sa.Text(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('created_on', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('author', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['author'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_group', sa.Enum('luminaire', 'power_tool', 'garden_tool', 'paint', name='productgroups'), nullable=False),
    sa.Column('brand', sa.String(length=20), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('sku', sa.Integer(), nullable=False),
    sa.Column('review', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('delete', 'update', 'active', 'oos', name='productstatus'), nullable=False),
    sa.Column('created_on', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('modified_on', sa.DateTime(), nullable=False),
    sa.Column('modified_by', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['modified_by'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['review'], ['product_reviews.id'], ),
    sa.ForeignKeyConstraint(['sku'], ['product_details.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_products',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_products')
    op.drop_table('products')
    op.drop_table('product_reviews')
    op.drop_table('employee_product_groups')
    op.drop_table('users')
    op.drop_table('product_details')
    op.drop_table('groups')
    op.drop_table('employees')
    # ### end Alembic commands ###
