"""remove nullable from modified_on

Revision ID: c8d942412261
Revises: 5e8477bb6381
Create Date: 2022-08-07 16:09:24.971424

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "c8d942412261"
down_revision = "5e8477bb6381"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("products", "review", existing_type=sa.INTEGER(), nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("products", "review", existing_type=sa.INTEGER(), nullable=False)
    # ### end Alembic commands ###
